export interface SignalProps {
  user: {
    avatar: string;
    username: string;
    rating: number;
    followers: number;
    address: string;
    online: boolean;
  };
  date: string;
  category: string;
  win_rate: number;
  total_trades: number;
  last_trades: number;
  total_profit: number;
  total_profit_rate: number;
  monthly_rol: number;
  daily: number;
  weekly: number;
  last_review: {
    user_avatar: string;
    username: string;
    rating: number;
    review: string;
  };
}

export const data = [
  {
    user: {
      avatar: "/assets/home/review-avatar2.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-1.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar3.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-2.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar4.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-3.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar5.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-5.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar6.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-6.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar7.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-7.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar1.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-8.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar2.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-9.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar3.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-10.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar4.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-11.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
  {
    user: {
      avatar: "/assets/home/review-avatar5.jpg",
      username: "Alpha Signals Pro",
      rating: 4.9,
      followers: 1243,
      address: "New York, USA",
      online: true,
    },
    date: "2 mins ago",
    category: "Scalping & Day Trading",
    win_rate: 87.5,
    total_trades: 342,
    last_trades: 34,
    total_profit: 15420.5,
    total_profit_rate: 21.1,
    monthly_rol: 23.1,
    daily: 2.3,
    weekly: 8.7,
    last_review: {
      user_avatar: "/assets/avatars/avatar-12.png",
      username: "TradeMaster_89",
      rating: 5,
      review: "Excellent signals with consistent profits!",
    },
  },
];
